import data from "./curriculum.json";
import type { PlanId } from "../plans";

export type Area = "numbers" | "ads" | "site" | "retention" | "learning";

export type CurriculumDay = {
  day: number;
  stage: number;
  stageName: string;
  topic: string;
  title: string;
  lesson: string;
  steps: string[];
  minutes: number;
  area: Area;
  learn: { slug: string; anchor: string; label: string; ref: string };
  sop: string;
  doIt: { tier: PlanId; label: string } | null;
  /** Which dashboard number shows the effect of this day's action. */
  watch: string | null;
};

export type Stage = { id: number; name: string; range: string };

/** Generated by scripts/build_curriculum.py from scripts/curriculum_source.py. */
export const STAGES = data.stages as Stage[];
export const DAYS = data.days as CurriculumDay[];

/** Minimum plan to unlock each stage of the guided daily programme. Learn lessons stay free. */
export const STAGE_TIER: Record<number, PlanId> = { 1: "free", 2: "free", 3: "starter", 4: "starter", 5: "starter", 6: "growth", 7: "growth" };

export const dayTaskId = (d: number) => `day-${d}`;

export const AREA_STYLE: Record<Area, { label: string; chip: string }> = {
  numbers: { label: "Numbers", chip: "bg-sky-50 text-sky-700 ring-sky-200" },
  ads: { label: "Ads", chip: "bg-violet-50 text-violet-700 ring-violet-200" },
  site: { label: "Site", chip: "bg-emerald-50 text-emerald-700 ring-emerald-200" },
  retention: { label: "Retention", chip: "bg-amber-50 text-amber-800 ring-amber-200" },
  learning: { label: "Mindset", chip: "bg-slate-100 text-slate-700 ring-slate-200" },
};
