export const STRATEGIES = [
  {
    id: "bfcm",
    emoji: "🛍️",
    title: "Black Friday / Cyber Monday playbook",
    desc: "A 12-week runway: revenue target, offer stack, list building, hype phase, launch, mid-sale drop and a calm finish.",
    helix: "Builds your timeline, models stock and budget, drafts emails and sale ads for your approval.",
    tone: "from-violet-500/15 to-indigo-500/10",
  },
  {
    id: "christmas",
    emoji: "🎁",
    title: "Christmas gifting",
    desc: "Gift guides, bundles, e-gift cards and clear delivery cut-offs so customers buy with confidence.",
    helix: "Suggests gift edits from your best sellers and reminds customers before shipping cut-offs.",
    tone: "from-emerald-500/15 to-teal-500/10",
  },
  {
    id: "valentines",
    emoji: "💌",
    title: "Valentine's and Mother's Day",
    desc: "Curated gift edits and gift-with-purchase offers that lift order value without store-wide discounts.",
    helix: "Plans the edit, writes the email and builds the ad batch, then waits for your OK.",
    tone: "from-rose-500/15 to-pink-500/10",
  },
  {
    id: "launch",
    emoji: "🚀",
    title: "New product launch",
    desc: "Waitlist, VIP early access, launch day, a 24-hour mid-launch drop and review collection.",
    helix: "Creates the launch checklist, hype emails and creative briefs.",
    tone: "from-cyan-500/15 to-sky-500/10",
  },
  {
    id: "abandoned",
    emoji: "🛒",
    title: "Abandoned cart recovery",
    desc: "Browse, cart and checkout flows timed right, with discounts for new customers only.",
    helix: "Audits your flows, fixes timing and drafts missing emails in your email platform.",
    tone: "from-amber-500/15 to-orange-500/10",
  },
  {
    id: "hooks",
    emoji: "🎬",
    title: "Winning UGC ad hooks",
    desc: "Native-feeling creator ads that win the first three seconds: one-star rebuttals, price shocks, result-first.",
    helix: "Writes briefs from your reviews, grades every test and tells you why winners won.",
    tone: "from-fuchsia-500/15 to-violet-500/10",
  },
  {
    id: "welcome",
    emoji: "👋",
    title: "Email welcome flow",
    desc: "Three to six emails that turn new subscribers into first-time buyers, often around 5% of revenue.",
    helix: "Drafts the flow from your brand voice and best sellers for you to approve.",
    tone: "from-lime-500/15 to-emerald-500/10",
  },
  {
    id: "daily",
    emoji: "📈",
    title: "The daily profit loop",
    desc: "Fifteen minutes a day: scorecard, one ad action, one site action, one retention action, one lesson.",
    helix: "Picks the three tasks that matter most today, and does them when you say so.",
    tone: "from-sky-500/15 to-indigo-500/10",
  },
];
