# "Just starting" track: for new founders with little or no sales yet.
# Lighter lessons (5 to 15 minutes), in plain English. Same day format as curriculum_source.py:
# (unused, topic, title = today's action, why it matters, numbered steps, minutes, area,
#  lesson ref "M.L", SOP, doIt (tier, label) or None, what to watch or None)
# Run: python3 scripts/build_curriculum.py

STAGES = [
    (1, "Check your product and offer", 7),
    (2, "Set up your Shopify store", 20),
    (3, "Your first small test campaign", 28),
]

D = [
 # ---------- Stage 1: Check your product and offer ----------
 (1, "Who it is for", "Write who your product is for",
  "If you try to sell to everyone, your ads and pages speak to no one. One clear sentence about your buyer makes every later step easier.",
  ["Finish this sentence: 'My product is for [person] who wants [result] but struggles with [problem].'",
   "Keep it under 25 words.",
   "Read it to a friend. Ask them to say it back in their own words.",
   "If they get it wrong, make the sentence simpler and try again.",
   "Save the final sentence. You will use it in your ads and on your home page."],
  10, "learning", "4.2", "16", None, None),
 (2, "Is there demand?", "Check that people already want it",
  "The cheapest test is the one you run before spending on ads. If people already search for, talk about and buy products like yours, you are in a good place.",
  ["Search Google for what you sell. Write down 3 competitors that come up.",
   "Read 20 reviews of those competitors. Note what people love and what they complain about.",
   "Search TikTok or Instagram for the product type. Do people post about it?",
   "Give your idea a score from 1 to 5 for demand. Under 3? Look at how to make the product or offer more different."],
  15, "learning", "3.7", "16", None, None),
 (3, "Your cost per sale", "Work out what one sale really costs you",
  "A sale can lose money even at a good price. You need to know every cost that comes with one order before you set prices or spend on ads.",
  ["Write your product cost (what you pay the supplier for one unit).",
   "Add packaging and the shipping you pay to send it.",
   "Add payment fees. Use about 3% of the price if you are not sure.",
   "Add the total. This is your cost per sale before ads.",
   "Price minus this cost is what you have left to pay for ads and keep as profit."],
  10, "numbers", "1.2", "02", ("free", "Work out your cost per sale from your prices"), None),
 (4, "A price that leaves profit", "Check your price leaves room for ads",
  "New stores often price too low and then cannot afford ads. A simple check now saves months of selling at a loss.",
  ["Take your price and your cost per sale from yesterday.",
   "Aim for a price of at least 3 times your product cost. Many small stores need this to cover ads and still make money.",
   "If you are below that, look at bundles, a higher-value version, or a cheaper supplier.",
   "Write down the most you could pay in ads for one sale and still break even: price minus cost per sale."],
  10, "numbers", "3.6", "04", None, None),
 (5, "Your promise", "Write your one-line promise",
  "People decide in seconds. A clear promise tells them what they get and why it is better, before they scroll away.",
  ["Write one line: the result your customer gets, not the features.",
   "Add why it is different, in plain words. For example: 'Soft as cotton, dries in an hour.'",
   "Cut any word a 12-year-old would not understand.",
   "Put the line at the top of your home page and under your product title."],
  10, "site", "3.2", "04", ("starter", "Draft 5 promise lines for you to choose from"), "Conversion rate"),
 (6, "Remove the risk", "Make buying feel safe",
  "A new store has no reputation yet. Clear returns, a simple guarantee and visible contact details make a stranger feel safe enough to buy.",
  ["Write your returns rule in one plain sentence, for example '30 days to change your mind'.",
   "Add it near the Add to cart button and in your footer.",
   "Show a real email address or chat button on every page.",
   "If you can, add a guarantee in one line."],
  10, "site", "3.5", "04", None, "Conversion rate"),
 (7, "First proof", "Collect your first reviews and photos",
  "People trust other customers more than they trust you. Even 5 honest reviews with photos make a big difference for a new store.",
  ["List everyone who has bought or tried the product, including friends and family.",
   "Ask each one for a short honest review and, if possible, a photo.",
   "Install a review app on your store if you do not have one.",
   "Add the best 3 reviews near the top of your product page."],
  15, "site", "3.3", "16", None, "Conversion rate"),

 # ---------- Stage 2: Set up your Shopify store ----------
 (8, "Plan the store", "Plan your store before you build",
  "Building without a plan means pages nobody needs and missing pieces you find too late. Twenty minutes of planning saves days.",
  ["Write your one-line promise from Day 5 at the top of a page.",
   "List each product with its price, product cost and cost to send one order.",
   "Pick one launch country (Australia or the US) and a Shopify plan from the pricing page.",
   "Gather your logo, 4 to 8 photos per product, your returns rule and your ABN (AU) or business details (US)."],
  15, "learning", "22.1", "11", None, None),
 (9, "Domain and email", "Connect your own domain and email",
  "A store on its own web address looks more trustworthy than a free myshopify.com address, and emails from your domain are less likely to land in spam.",
  ["Buy a short domain that matches your brand in Shopify, or connect one you own.",
   "Australia: a .com.au needs an ABN. US: a .com is the normal choice.",
   "Make your own domain the main one customers see.",
   "Set up hello@yourbrand (or similar) and send yourself a test email."],
  15, "site", "22.2", "11", None, None),
 (10, "Theme", "Pick a free theme and set your brand basics",
  "A fast, simple theme beats a fancy slow one. Setting colours and fonts once keeps every page looking the same.",
  ["In Online Store, open Themes. Start with a free theme such as Dawn.",
   "Duplicate the theme and make changes on the copy.",
   "In Theme settings, set your logo, 2 to 3 colours, 1 to 2 fonts and button style.",
   "Preview on your phone before you publish."],
  15, "site", "22.3", "11", None, None),
 (11, "Home page", "Build a home page that makes sense in 5 seconds",
  "Visitors who are confused leave. The top of your home page must say what you sell, who it is for and why to trust you.",
  ["Add a promo bar with one short line, such as your shipping offer.",
   "Keep the menu to 4 to 5 links.",
   "Add a banner: a clear product photo, your promise line and one 'Shop now' button.",
   "Below it add best sellers, reasons to buy, reviews and how it works.",
   "Ask someone new to look for 5 seconds and say what you sell."],
  15, "site", "22.4", "11", ("free", "Run a store check-up on your home page"), "Conversion rate"),
 (12, "Product page", "Set up your first product page",
  "Most buying decisions happen on the product page. Answering worries up front turns visitors into buyers.",
  ["Add the product with a short title: name plus what it is or does.",
   "Upload at least 4 photos: plain background, in use, size, close-up.",
   "Put price, rating and Add to cart near the top. Write the description as short lines.",
   "Add a short FAQ: sizing, materials, shipping time, returns.",
   "Fill in product cost so Helix can work out your profit."],
  15, "site", "22.5", "11", ("starter", "Draft product page copy for your top product"), "Conversion rate"),
 (13, "Options, stock and reviews", "Add variants, stock and a review app",
  "Wrong stock numbers cause oversold orders and refunds. Reviews near the top of the page build trust from day one.",
  ["Add options such as size or colour as variants of one product.",
   "Give each variant a photo, SKU, stock count, cost and weight. Turn on Track quantity.",
   "Install one review app that asks for photo reviews after delivery.",
   "Ask early buyers or testers for honest reviews. Never write fake ones."],
  15, "site", "22.6", "16", None, "Conversion rate"),
 (14, "Collections and menu", "Group products and build your menu",
  "If people cannot find a product quickly, they leave. A short menu and clear groups get them there in a few taps.",
  ["Make collections: Best sellers, New, and one per product type.",
   "Build the main menu with 4 to 5 links. Put product types in a drop-down.",
   "Turn on filters for size, colour, price and in stock.",
   "Search for your top 5 product words and fix anything that does not show up."],
  15, "site", "22.8", "11", None, None),
 (15, "Shipping", "Set shipping rates and a free-shipping amount",
  "Surprise shipping costs are one of the top reasons people leave at checkout. Clear rates and a free-shipping amount fix that and lift order size.",
  ["In Settings, open Shipping and delivery and set up your home country.",
   "Add a Standard and an Express rate from your real carrier costs.",
   "Set free shipping over an amount about 1.3 times your average order.",
   "Show delivery as a range, such as '3 to 6 business days', on the product page."],
  15, "site", "22.9", "11", None, "Conversion rate"),
 (16, "Taxes and payments", "Check your tax settings and turn on payments",
  "Getting tax wrong is costly to fix later, and every missing payment option loses buyers. This is general information, not tax advice.",
  ["Australia: check if you need GST (register at $75,000 GST turnover). If registered, add your ABN and include GST in prices.",
   "US: turn on sales tax only for states where you have registered.",
   "Activate Shopify Payments, Shop Pay, Apple Pay and Google Pay. Add PayPal.",
   "Set your statement name to your brand. Ask a registered tax agent or accountant if unsure."],
  15, "numbers", "22.10", "11", None, None),
 (17, "Policies", "Write your policies in plain words",
  "Clear policies build trust and keep you within consumer law. Templates are a start, but they need your own details.",
  ["Create Refund, Privacy, Terms, Shipping and Contact pages from Shopify's templates.",
   "Rewrite them in plain words with your own delivery ranges and cut-off dates.",
   "Australia: never write 'no refunds'. Customers always have rights for faulty items.",
   "Link every policy in the footer."],
  15, "site", "22.12", "11", None, None),
 (18, "Apps and email", "Add your starter apps and email sign-up",
  "Most visitors will not buy on the first visit. An email sign-up lets you invite them back for free. Keep apps few so the store stays fast.",
  ["Install only the starter set: reviews, email, and the Facebook and Google channels.",
   "Turn on a sign-up pop-up with a small reason to join.",
   "Write one welcome email: hello, your promise and your best seller.",
   "Sign up yourself to test it."],
  15, "retention", "22.13", "13", ("starter", "Draft your welcome email"), "Email sign-ups"),
 (19, "Tracking", "Install the Meta pixel and Google tag",
  "Without tracking you cannot tell which ads bring sales. Set it up before you spend a single dollar on ads.",
  ["Install the Facebook and Instagram app. Connect your Business account, ad account, Page and pixel.",
   "Set data sharing to Maximum to turn on server events.",
   "Install the Google and YouTube app and connect Merchant Center and Analytics.",
   "You will check both with a test order tomorrow."],
  15, "ads", "22.14", "05", None, None),
 (20, "Test and launch check", "Place a test order and tick the launch checklist",
  "A test order proves that payments, emails, stock and tracking all work together before real customers find a problem.",
  ["Check your store speed on a phone using mobile data.",
   "Turn on test mode and place an order on your phone.",
   "Check the email, stock, shipping, tax, and the Purchase in Meta and Google.",
   "Turn test mode off. Tick the pre-launch checklist and remove the store password."],
  15, "site", "22.16", "11", None, "Conversion rate"),

 # ---------- Stage 3: Your first small test campaign ----------
 (21, "Daily numbers", "Start your 2-minute morning numbers",
  "Even with few sales, writing down yesterday's sales, orders and ad spend each morning builds the habit that later tells you what is working.",
  ["Go to Today and find the 'Update yesterday' box.",
   "Type yesterday's sales and orders as your store shows them. Zero is fine. If your prices include GST, Helix takes it out for you (Settings).",
   "Type any ad spend.",
   "Press Save. Do this every morning from now on."],
  5, "numbers", "1.6", "02", None, "Profit, every day"),
 (22, "Test budget", "Set your test budget and your stop rule",
  "Your first campaign is a test, not a bet. Decide how much you can afford to learn with, and when to stop, before you start.",
  ["Pick a total test budget you can afford to lose, for example $150 to $300.",
   "Split it over 7 to 10 days. That is often $20 to $30 a day.",
   "Write your stop rule: if one ad spends twice your break-even cost per sale with no sale, turn it off.",
   "Write your keep rule: if an ad gets sales at or under your break-even cost, keep it running."],
  10, "numbers", "1.5", "06", None, "Ad cost per sale (CPA) compared with your break-even"),
 (23, "Simple ads", "Film 3 simple ads on your phone",
  "You do not need a studio. Simple, real-looking phone videos often beat polished ads, especially for new brands.",
  ["Film 3 short videos (10 to 20 seconds) on your phone in good daylight.",
   "Video 1: you or a customer using the product. Video 2: a close-up of the key detail. Video 3: the problem, then your product solving it.",
   "Hold the phone upright (vertical).",
   "Add short captions, because many people watch with the sound off."],
  15, "ads", "19.10", "08", None, None),
 (24, "Words that stop the scroll", "Write the first line for each ad",
  "The first 3 seconds and the first line decide if anyone watches. One clear line about the problem or result works best.",
  ["For each video, write a first line that names the problem or the result, for example 'Tired of bottles that leak in your bag?'",
   "Write a short main text: the promise, one proof point and the offer.",
   "Add a clear button such as 'Shop now'.",
   "Read each one out loud. Cut anything that sounds like an ad from a big company."],
  10, "ads", "5.7", "07", ("starter", "Draft 3 opening lines and ad text for each video"), None),
 (25, "Build the test", "Set up your first campaign, paused",
  "Building the campaign paused lets you check everything calmly before any money is spent.",
  ["In Ads Manager, create a Sales campaign.",
   "Set the daily budget from Day 22. Leave the audience broad (your country, adults).",
   "Add your 3 ads and link them to your best product page.",
   "Leave it paused. Check the link, the pixel and the text, then save."],
  15, "ads", "20.3", "05", ("starter", "Build the test campaign as a paused draft in your account"), None),
 (26, "Launch and wait", "Launch the test and leave it alone",
  "New campaigns go through a learning phase while Meta works out who to show them to. Changing things every day restarts it and wastes money.",
  ["Press Launch on your paused campaign.",
   "Do not change budgets or ads for 3 days unless an ad hits your stop rule.",
   "Keep doing your 2-minute morning numbers.",
   "Note each day's spend, clicks and any sales."],
  5, "ads", "7.5", "06", None, "Ad cost per sale (CPA) and profit"),
 (27, "Read the results", "Read what your test is telling you",
  "Even without many sales, the numbers show where the problem is: the ad, the page, or the offer.",
  ["Check how many people clicked (CTR, the share of viewers who click). Under about 1% often means the ad needs work.",
   "If people click but do not add to cart, the product page or price is the problem.",
   "If people add to cart but do not buy, check shipping costs and checkout.",
   "Write down the one biggest problem."],
  15, "ads", "20.7", "06", None, "Ad cost per sale (CPA) and profit"),
 (28, "Your next step", "Decide what to do next",
  "A test ends with a decision. Keep what works, fix the biggest problem, and plan the next small test.",
  ["Turn off any ad that broke your stop rule.",
   "Keep any ad that got sales at or under break-even.",
   "Pick one fix for the biggest problem from yesterday: a new ad, a page change, or a better offer.",
   "When you are getting regular sales, switch to the Growing track in Settings."],
  10, "learning", "7.6", "06", None, None),
]
