# Source of truth for the day-by-day curriculum, written in plain, simple English.
# Run: python3 scripts/build_curriculum.py  (writes src/lib/seed/curriculum.json and docs/daily-curriculum.md)
# Each day: (unused, topic, title = today's action, why it matters, numbered steps, minutes, area,
#            lesson ref "M.L", SOP, doIt (tier, label) or None, what to watch on the dashboard or None)
# Writing rules: short sentences. One idea per step. Explain any jargon (the app adds "Words to know").

# (id, name, last day of the stage). Days are renumbered in order by build_curriculum.py.
STAGES = [
    (1, "Know your numbers", 7),
    (2, "Turn more visitors into buyers", 17),
    (3, "Get customers to come back", 26),
    (4, "Make ads that sell", 46),
    (5, "Google and other channels", 52),
    (6, "Sales, launches and busy season", 58),
    (7, "Grow bigger, work smarter", 64),
]

D = [
 # ---------- Stage 1: Know your numbers ----------
 (1, "Profit, not sales", "Tell Helix your costs",
  "Sales show how busy you were. Profit shows what you kept. To work out your profit every day, Helix needs to know your costs. This takes 10 minutes and you only do it once.",
  ["Open Your numbers (the scorecard) and find the Settings box.",
   "Type your monthly fixed costs. These are bills that stay the same, like rent, software, staff and your own wage.",
   "Type a monthly sales target you believe you can hit.",
   "Type a target MER. If you are not sure, use 30%.",
   "Press Save."],
  10, "numbers", "1.2", "02", ("free", "Fill in your costs from your store data"), "Profit at the top of your dashboard"),
 (2, "Your daily numbers", "Add yesterday's numbers",
  "Two minutes each morning tells you if yesterday made money. Doing this every day is the habit that makes everything else work.",
  ["Go to Today and find the 'Update yesterday' box at the top.",
   "Type yesterday's sales and number of orders.",
   "Check the ad spend. If Meta is connected, Helix fills it in for you.",
   "Press Save.",
   "Read the big profit number and the one line under it."],
  5, "numbers", "1.3", "02", ("starter", "Pull yesterday's numbers in for you each morning"), "Profit, every day"),
 (3, "Break-even", "Find the most you can pay for a sale",
  "Every ad decision needs a line in the sand. Break-even is the point where a sale makes $0. Spend less than that per sale and you make money. Spend more and you lose money.",
  ["Open Your numbers (the scorecard).",
   "Find 'Break-even ROAS' and 'Break-even CPA' in the channel box. Helix works these out for you.",
   "Write both numbers down.",
   "Write your target cost per sale too. Helix shows it next to the break-even number.",
   "Stick the note where you will see it when you check your ads."],
  10, "numbers", "1.5", "02", None, "Ad cost per sale (CPA) compared with your break-even"),
 (4, "Find the bottleneck", "Find the one thing holding profit back",
  "Profit usually stalls for one of three reasons: costs are too high, too few visitors buy, or not enough people visit. Fixing the wrong one wastes months. Today you find the right one.",
  ["Open Your numbers (the scorecard) and look at the coloured flags.",
   "Find the number with a red flag. If there is none, pick the amber one.",
   "Open Lesson 2.2 and find the matching situation.",
   "Write down one fix to work on this week."],
  15, "numbers", "2.2", "03", ("starter", "Look at your numbers and tell you the bottleneck"), "The flagged number on Your numbers"),
 (5, "Store check-up", "Pick your top 3 store fixes",
  "Helix checks your store for speed, reviews, clear shipping info, email sign-up and trust signs. You pick the three fixes that matter most.",
  ["Open Insights.",
   "Read the store check-up list on the right.",
   "Pick three red or amber items you can each fix in under an hour.",
   "Put them in your calendar for this week."],
  10, "site", "9.2", "01", ("free", "Run a fresh store check-up"), "Conversion rate"),
 (6, "Listen to customers", "Read 30 reviews and 10 customer emails",
  "Your customers already wrote your best ads. Their words show the problem they had, what worried them, and why they bought.",
  ["Open your last 30 reviews and 10 customer emails.",
   "Copy phrases that come up again and again into a document.",
   "Sort them under three headings: the problem, the worry, the result.",
   "Write down the top 3 worries.",
   "Star 5 lines that could start an ad."],
  20, "learning", "4.2", "16", ("starter", "Read your reviews and pull out the themes"), None),
 (7, "Weekly check-in", "Do your first weekly review",
  "Small daily actions add up when you look back each week. Ten minutes on Sunday or Monday keeps you on track.",
  ["Open Your numbers (the scorecard) and look at this week's profit.",
   "List what you did this week.",
   "Write one thing you learned.",
   "Pick one priority for next week."],
  10, "learning", "16.2", "18", None, "Profit this week compared with last week"),
 # ---------- Stage 2: Turn more visitors into buyers ----------
 (8, "Speed", "Fix the biggest speed problem on your phone",
  "Most shoppers use a phone. If your product page is slow, they leave before they see what you sell.",
  ["Open Insights and find your mobile speed score.",
   "Make the big photos on your best product page smaller in file size.",
   "Remove one app or plug-in you no longer use.",
   "Test the speed again and write down the new score."],
  20, "site", "9.4", "11", ("growth", "Write a speed fix list for your developer"), "Conversion rate"),
 (9, "Reviews", "Put photo reviews near the price on your best seller",
  "Reviews close to the price help people decide. It is one of the cheapest ways to get more sales from the same visitors.",
  ["Open your best-selling product page.",
   "Pick 3 reviews with photos that answer common worries.",
   "Place them just under the price or the Add to cart button.",
   "Check how it looks on your phone."],
  10, "site", "9.2", "11", ("growth", "Lay out the review section for you"), "Conversion rate"),
 (10, "Answer worries", "Answer your top 3 worries on the product page",
  "If shoppers have to guess about size, quality or delivery, they leave. Answer their worries before they ask.",
  ["Take the 3 worries you found on Day 6.",
   "Write a one-line answer for each.",
   "Add them near the Add to cart button as short questions and answers or icons.",
   "Link to your guarantee or returns page."],
  15, "site", "3.3", "04", ("starter", "Write the answers for you"), "Conversion rate"),
 (11, "Shipping", "Set a free shipping amount that makes orders bigger",
  "If free shipping starts a little above your usual order, many people add one more item to reach it.",
  ["Find your AOV (average order value) on Your numbers.",
   "Multiply it by 1.3. Round to a simple number. That is your free shipping amount.",
   "Show it in the bar at the top of your store and in the cart.",
   "Check you still make a profit on an order of that size."],
  15, "site", "9.11", "12", ("growth", "Set up the free shipping message (after you approve)"), "AOV (average order value)"),
 (12, "Checkout", "Remove one thing that stops people paying",
  "People who add to cart but do not pay usually hit a surprise: a shipping cost, too few ways to pay, or being forced to make an account.",
  ["Do a test order on your phone.",
   "Turn on Apple Pay, Google Pay and Shop Pay if they are missing.",
   "Turn on buy now pay later (like Afterpay) if it suits your products.",
   "Let people check out without an account.",
   "Show the delivery time before the last step."],
  15, "site", "9.10", "11", None, "Conversion rate"),
 (13, "Home page", "Make the top of your home page say what you sell",
  "Visitors decide in a few seconds. The first screen needs a clear headline, the main benefit, some proof and one button.",
  ["Open your home page on your phone.",
   "Rewrite the headline: what it is, plus the main benefit.",
   "Add one proof line, like your star rating or number of customers.",
   "Keep one clear button."],
  15, "site", "9.5", "11", ("starter", "Write 3 headline options for you"), "Conversion rate"),
 (14, "Guarantee", "Write a guarantee you are proud of",
  "A clear promise removes the fear of a bad purchase. It often helps sales more than a discount, and it costs less.",
  ["Read your current returns policy.",
   "Write a simple promise in one sentence. Example: 'Love it or send it back within 30 days.'",
   "Add it to your product pages, cart and FAQ page.",
   "Check your team can keep the promise."],
  10, "site", "3.5", "04", ("starter", "Write your guarantee for you"), "Conversion rate"),
 (15, "Bundles", "Make one bundle that raises order size",
  "A bundle sells the full solution in one go. It makes orders bigger without a store-wide discount.",
  ["Find two or three products people often buy together.",
   "Make one bundle with a small saving or a free gift.",
   "Show it on the matching product pages.",
   "Watch how many sell in the product table on Your numbers."],
  20, "site", "3.6", "12", ("growth", "Suggest bundles from your order history"), "AOV (average order value)"),
 (16, "Menu", "Tidy your menu and your best collection page",
  "If people cannot find it, they cannot buy it. A simple menu and clear collections make shopping easy.",
  ["Cut your menu down to the main ways people shop, like by product type.",
   "Put your best sellers first on your main collection page.",
   "Add filters for size or type if you have many products.",
   "Search your store for a common product and check the results make sense."],
  20, "site", "9.2", "11", None, "Conversion rate"),
 (17, "After checkout", "Add a one-click offer after people buy",
  "Right after buying, trust is at its highest. A small, related extra at a small saving makes orders bigger.",
  ["Pick a low-cost product that goes with your best seller.",
   "Set up an after-purchase offer in your checkout app.",
   "Keep it to one offer.",
   "Next week, check how many people said yes."],
  15, "site", "9.10", "12", ("growth", "Set up the offer (after you approve)"), "AOV (average order value)"),
 # ---------- Stage 3: Get customers to come back ----------
 (18, "Email sign-up", "Add a pop-up that gets 3 or more sign-ups per 100 visitors",
  "Most visitors leave without buying. A pop-up lets you keep in touch with them by email, for free, forever.",
  ["Pick a reward: 10% off, free shipping or a useful guide.",
   "Show the pop-up after 8 to 10 seconds, or when someone is about to leave.",
   "Ask for email first. Ask for a phone number on the next step.",
   "Check the sign-up rate every week."],
  20, "retention", "10.1", "13", ("growth", "Write the pop-up and choose the settings for you"), "Email sign-ups in your email platform"),
 (19, "Welcome emails", "Turn on your welcome emails",
  "New subscribers are most interested right after they sign up. A short series of welcome emails turns many of them into first-time buyers, even while you sleep.",
  ["Open Email automation in Helix.",
   "Read the welcome email drafts.",
   "Press Approve.",
   "Check it is switched on in your email platform.",
   "Send yourself a test."],
  20, "retention", "10.2", "13", ("growth", "Write and set up your welcome emails"), "Email sales and profit"),
 (20, "Checkout reminders", "Turn on checkout reminder emails",
  "People who started checkout were very close to buying. A friendly reminder brings many back, usually without a discount.",
  ["Open Email automation.",
   "Read the checkout reminder drafts.",
   "Only offer a discount to new customers, and only in the last email.",
   "Approve and send yourself a test."],
  15, "retention", "10.2", "13", ("growth", "Write and set up checkout reminders"), "Email sales and profit"),
 (21, "Cart and browse reminders", "Add cart and browsing reminders",
  "Not everyone reaches checkout. Gentle reminders help people who looked or added to cart make up their mind.",
  ["Read the cart and browsing reminder drafts.",
   "Add a 'best sellers' block or a short buying guide.",
   "Make sure people who already ordered do not get them.",
   "Approve and send yourself a test."],
  15, "retention", "10.2", "13", ("growth", "Write and set up both reminder series"), "Email sales and profit"),
 (22, "After the order", "Set up thank-you and review emails",
  "What happens after the first order decides if there is a second. Say thank you, help them use the product, then ask for a review.",
  ["Read the after-order and review request drafts.",
   "Send the review request when customers will have seen results.",
   "Add tips on how to use the product.",
   "Approve and send yourself a test."],
  15, "retention", "10.2", "13", ("growth", "Write and set up both email series"), "Returning customer sales"),
 (23, "Repeat customers", "Plan emails for lapsed, reorder and best customers",
  "Different customers need different messages. Remind people who stopped buying. Remind people when they are about to run out. Reward your best customers.",
  ["Work out the usual number of days between orders.",
   "Choose which of the three email series fit your products.",
   "Read the drafts.",
   "Approve the ones that fit."],
  20, "retention", "10.12", "13", ("growth", "Write and set up the series that fit"), "Returning customer sales"),
 (24, "Weekly emails", "Plan two emails a week",
  "Automatic emails catch key moments. Weekly emails build the relationship. Mix helpful tips, stories, products and the odd offer.",
  ["Pick two send days each week.",
   "Plan 4 weeks of topics: a story, a tip, best sellers, new arrivals.",
   "Send more often to people who open your emails, less to people who do not.",
   "Schedule next week's first email."],
  20, "retention", "10.5", "14", ("growth", "Write next week's emails"), "Email sales and profit"),
 (25, "Text messages", "Decide if text messages suit your store",
  "Text messages get read fast but cost more than email. Save them for big moments.",
  ["Check how much each text costs in your email platform.",
   "Add a phone number step to your pop-up.",
   "Use texts for launches, sale starts and checkout reminders only.",
   "Always include a way to unsubscribe."],
  10, "retention", "10.10", "13", None, None),
 (26, "Grow your list", "Plan a giveaway with partner brands",
  "A giveaway run with a few friendly brands can add thousands of new subscribers before a big sale.",
  ["Pick a prize your ideal customer wants. Not cash.",
   "Invite 2 to 4 brands that sell to the same people but do not compete with you.",
   "Ask for email and phone to enter. Give extra entries for sharing.",
   "Plan a welcome offer for new people who enter."],
  20, "retention", "11.3", "14", ("growth", "Write the giveaway plan and partner messages"), "Email sign-ups in your email platform"),
 # ---------- Stage 4: Make ads that sell ----------
 (27, "Your brand", "Write your brand on one page",
  "When you are clear on who you serve and how you sound, every ad, email and page gets easier to write.",
  ["Write what your business does in one sentence.",
   "Describe your best customer.",
   "List 3 things you do differently from others.",
   "Pick 3 words for how you sound, like friendly, expert, funny."],
  20, "learning", "4.1", "16", ("starter", "Write a first draft from your website"), None),
 (0, "Social profile", "Make your Instagram and TikTok profiles sell",
  "Many people who see your ad tap your profile before they buy. Your profile should show you are real, show what you sell and tell them what to do next.",
  ["Rewrite your bio: what you sell, one proof point, a reason to tap.",
   "Point your link to a fast page with 3 to 5 clear choices.",
   "Make story highlights for Reviews, Best sellers, How to use and Shipping.",
   "Pin three posts: your best product video, your best review and your story."],
  20, "learning", "21.2", "16", ("starter", "Check your profiles and write your bio and highlights"), None),
 (0, "Posting plan", "Pick a posting plan you can keep for 12 weeks",
  "Posting regularly beats posting a lot. A simple weekly plan keeps your profile alive and gives you tested ideas for ads.",
  ["Pick how often to post for your stage (Lesson 21.4).",
   "Plan next week using four types of post: proof, tips, story and product.",
   "Film everything on one day.",
   "Schedule the posts."],
  25, "learning", "21.4", "16", ("starter", "Write a 4-week posting calendar"), None),
 (0, "Free reach", "Test new video openings on people who do not follow you",
  "People now search inside Instagram and TikTok. Say what you sell out loud and on screen. Test new openings on non-followers first.",
  ["Pick your best video.",
   "Make 3 new versions of the first 3 seconds. Say your key words out loud and show them on screen.",
   "Post them as trial reels where that option exists.",
   "After 24 hours, share the best one with everyone and save it as an ad idea."],
  20, "learning", "21.5", "16", None, None),
 (28, "Ad ideas", "Write ad ideas for people at different stages",
  "Some people do not know they have a problem. Others are comparing options. Each group needs a different message.",
  ["List 3 problems your product solves.",
   "Write one ad idea for each group: does not know the problem, knows the problem, is comparing products.",
   "Pick one idea to test first.",
   "Save them all in a list for later."],
  20, "ads", "5.5", "07", ("starter", "Suggest ad ideas for each group"), None),
 (29, "Openings", "Write 20 ad openings",
  "The first 3 seconds decide if anyone watches. The best openings come from your customers' own words.",
  ["Use your notes from Day 6.",
   "Write 20 opening lines. Mix bold claims, questions, surprising facts and 'before and after'.",
   "Add a picture idea for each.",
   "Star your top 5."],
  20, "ads", "19.8", "07", ("starter", "Write 20 openings from your reviews"), None),
 (30, "Creators", "Make a list of 10 creators",
  "Real people saying why they love your product build trust faster than brand ads. A good match matters more than follower count.",
  ["Search Instagram and TikTok for the problem your product solves.",
   "Check posts where customers tagged you.",
   "Give each creator a score out of 10 for fit.",
   "Save your top 10 in the creator list."],
  20, "ads", "19.2", "08", ("starter", "Find creators that suit your store"), None),
 (31, "Contact creators", "Message 5 creators with a product and commission offer",
  "Start by sending free product. Pay more once their content sells. Make sure their discount code is not beaten by your own pop-up offer.",
  ["Write a personal message that mentions one of their videos.",
   "Offer free product plus a commission on sales they bring.",
   "Check your public discounts are not bigger than their code.",
   "Send 5 messages today and note who you contacted."],
  20, "ads", "19.5", "08", ("starter", "Write personal messages for you"), None),
 (32, "Creator brief", "Write a one-page brief for creators",
  "A clear brief means you get videos you can use. Put the main message, proof, openings and what to deliver on one page.",
  ["Open the brief template in Lesson 19.12.",
   "Fill in the main message, proof points and anything they must not say.",
   "Add 3 openings for them to film separately.",
   "Send it to your creators."],
  20, "ads", "19.12", "08", ("starter", "Fill in the brief for you"), None),
 (33, "Video script", "Write one 30-second video ad",
  "A simple order keeps videos short and selling: opening, problem, product and proof, answer a worry, tell them what to do.",
  ["Pick your best ad idea and opening.",
   "Write the script in those five parts.",
   "Read it out loud and cut anything slow.",
   "Write 3 other openings to test."],
  20, "ads", "19.9", "07", ("starter", "Write 3 script options for you"), None),
 (34, "Film it", "Film and edit a video on your phone",
  "You do not need a studio. Window light, clear sound, quick cuts and captions do better on social media than polished ads.",
  ["Film next to a window, holding the phone upright, with the back camera.",
   "Film the opening 3 different ways.",
   "Edit: quick cuts, captions, and the opening line written on screen in the first frame.",
   "Save it in two sizes: tall (9:16) and portrait (4:5)."],
  45, "ads", "19.11", "07", None, None),
 (35, "Tracking", "Check Meta is counting your sales correctly",
  "If your sales are counted wrong, every ad decision will be wrong. Make sure each sale is counted once, with the right amount.",
  ["Check your pixel and server events are connected in Meta Events Manager.",
   "Make 'Purchase' the main result you track.",
   "Place a test order and check it shows up once, with the right value.",
   "Add UTM tags to your ad links."],
  15, "ads", "20.1", "05", ("starter", "Check your tracking for you"), "Meta sales compared with your store's real sales"),
 (36, "Audiences", "Set up your audiences",
  "Showing ads to a wide audience with strong ads usually works best. You still need lists of visitors and customers so you can treat them differently.",
  ["In Meta, mark your engaged people and existing customers.",
   "Create lists of: visitors in the last 30 and 180 days, people who added to cart, people who started checkout, buyers.",
   "Upload your customer email list.",
   "Create one lookalike audience to test later."],
  20, "ads", "20.2", "05", ("starter", "Create the audiences in your account (after you approve)"), None),
 (37, "Plan the campaign", "Fill in a campaign plan",
  "Every campaign starts with numbers and a 'stop' rule, not with Ads Manager. Writing the plan first makes later decisions easy.",
  ["Open the campaign plan template.",
   "Write your target cost per sale, daily budget and how many days you will test.",
   "Choose the goal (Sales) and who it is for (new or returning people).",
   "Write when you will stop an ad and when you will spend more on it."],
  20, "ads", "6.16", "05", ("starter", "Fill in the plan with you"), None),
 (38, "Build the campaign", "Build your first Meta sales campaign",
  "Follow the steps carefully once. Then you can repeat them for every test. Helix can build it for you as a paused draft, and you press Launch.",
  ["Create a Sales campaign and name it with your naming pattern.",
   "Set the daily budget at 2 to 3 times your target cost per sale.",
   "Add 3 to 6 ads that test one thing, like different openings.",
   "Check the preview, then press Launch yourself."],
  30, "ads", "20.3", "05", ("starter", "Build it in your account as a paused draft. You press Launch"), "Ad cost per sale (CPA) and profit"),
 (39, "Keep it simple", "Match your ad account to your budget",
  "Small budgets need simple setups. Add more campaigns only as you spend more.",
  ["Find your daily spend in the table in Lesson 6.4.",
   "Compare it with how many campaigns you have running.",
   "Join together or pause the ones that do not fit.",
   "Rename campaigns to your naming pattern."],
  15, "ads", "6.4", "05", ("starter", "Suggest a simpler setup"), "Ad cost per sale (CPA)"),
 (40, "Daily ad check", "Check your ads and stop the money-wasters",
  "Ten minutes a day: stop ads that spent twice your target cost per sale with no sales, give more to winners, and leave new ads alone for a few days.",
  ["Open Your ads in Helix.",
   "Read Helix's advice next to each campaign.",
   "Pause the ones marked Stop. For ones marked Spend more, raise the budget by up to 20% yourself in Ads Manager.",
   "Write down what you changed."],
  10, "ads", "7.6", "06", ("starter", "Pause the money-wasters for you (after you approve) and tell you which budgets to raise"), "Profit and ad cost per sale (CPA)"),
 (41, "Find the leak", "Find where you are losing buyers",
  "Good ad but few sales means the page needs work. Lots of carts but few orders means checkout. A strong site but few clicks means the ad. Find the leak before you fix anything.",
  ["Open Insights.",
   "Read what Helix found.",
   "Match each finding to the table in Lesson 20.7.",
   "Pick one fix for this week."],
  15, "ads", "20.7", "06", ("starter", "Explain where you are losing buyers"), "Conversion rate"),
 (42, "Creator ads", "Run one ad from a creator's account",
  "An ad from a creator's own account shows a familiar face instead of a brand. Add it to your normal campaign.",
  ["Ask a creator with a strong post for permission.",
   "Connect with them using Meta's partnership ad tools.",
   "Add the post to your campaign for new customers.",
   "Judge it with the same rules as your other ads."],
  20, "ads", "19.6", "08", ("starter", "Add it to your campaign as a paused ad"), "Ad cost per sale (CPA)"),
 (43, "Weekly ad review", "Do your weekly ad review",
  "Your best ads tell you what to make next. Make new versions of the winner with new openings, people and formats.",
  ["List last week's top 3 ads by cost per sale and hook rate.",
   "Write why you think each one worked.",
   "Plan 4 to 8 new versions.",
   "Turn off ads that have stopped working."],
  20, "ads", "5.11", "07", ("starter", "Make your weekly ad report"), "Ad cost per sale (CPA)"),
 # ---------- Stage 5: Google and other channels ----------
 (44, "Product titles", "Rewrite titles for your top 10 products",
  "Google shopping ads match what people search to your product titles. Using the words people search is the biggest win.",
  ["Find the search words that led to sales.",
   "Rewrite titles in this order: brand, product type, main feature, size or colour.",
   "Check photos and prices are right.",
   "Send the updated product list to Google again."],
  25, "ads", "8.2", "09", ("starter", "Rewrite your product titles (after you approve)"), "Google sales and profit"),
 (45, "Google setup", "Set up brand search and a shopping campaign",
  "Keep cheap searches for your brand name in their own campaign. Then let a shopping campaign find new customers, with your brand name left out.",
  ["Create or check a campaign for searches of your brand name.",
   "Create a Performance Max campaign that only uses your product list, with your brand name excluded.",
   "Start with the 'maximise conversion value' setting.",
   "Put a date in your calendar to review it in 2 weeks."],
  30, "ads", "20.4", "09", ("starter", "Build both campaigns as paused drafts"), "Google sales and profit"),
 (46, "Wasted searches", "Block searches that waste money",
  "Searches that cost money but never sell are pure waste. Ten minutes a week stops the leak.",
  ["Open the search terms report in Google Ads.",
   "Sort by cost, highest first.",
   "Add searches that have nothing to do with your products as negative keywords.",
   "Add searches that sell to your product titles."],
  10, "ads", "8.8", "09", ("starter", "Find and block wasted searches (after you approve)"), "Google ad spend and profit"),
 (47, "TikTok", "Decide if TikTok is right for you yet",
  "TikTok rewards fun, natural videos and lots of them. Get ready before you spend money there.",
  ["Go through the checklist in Lesson 12.1.",
   "Post 3 videos (no ads) this week.",
   "Save your best creator videos to use as TikTok ads later.",
   "Decide: start now or next quarter."],
  15, "ads", "12.1", "10", None, None),
 (48, "Google search basics", "Fix the basics on your top pages",
  "Showing up in Google search is free traffic that grows over time. Start with titles, descriptions and helpful text on your best pages.",
  ["Write a unique page title and meta description for your top 5 pages.",
   "Add a short helpful paragraph to your main collection page.",
   "Fix any broken links.",
   "Submit your sitemap in Google Search Console."],
  25, "site", "12.8", "10", ("growth", "Write titles and descriptions for you"), "Sessions from Google search"),
 (49, "AI shopping", "Get ready for AI shopping assistants",
  "Shoppers now ask AI assistants what to buy. Clear product details and policies make it easier for them to recommend you.",
  ["Check every top product has full details: size, material, use.",
   "Make returns and shipping rules easy to find and read.",
   "Check if your store platform lets AI assistants show your products.",
   "Add common questions and answers to your top products."],
  15, "site", "12.9", "10", None, None),
 # ---------- Stage 6: Sales, launches and busy season ----------
 (50, "Sales calendar", "Plan your next 90 days of promotions",
  "Planned moments beat random discounts. Mix new products, gift ideas and a few real sales.",
  ["List key dates for your customers.",
   "Plan one moment per month: a launch, a gift guide or a sale.",
   "Decide the type of offer for each.",
   "Put them in your calendar."],
  20, "retention", "13.1", "15", ("growth", "Write your promotions calendar"), "Profit during each promotion"),
 (51, "Sale offers", "Design a sale offer that keeps your profit",
  "Spend-more-save-more offers, free gifts and bundles often beat big discounts. Check every offer still makes a profit.",
  ["Pick an offer type: spend-more-save-more, free gift, bundle or percent off.",
   "Check the profit on Your numbers at the new price.",
   "Plan a boost halfway through the sale.",
   "Write the offer in one line."],
  20, "retention", "13.4", "15", ("growth", "Work out the profit on each offer"), "Profit during the sale"),
 (52, "Black Friday", "Start your Black Friday plan",
  "The biggest sale of the year is won months before it starts. Planning begins in August: test ads and offers early, then set your target, offer, stock, email list, ads and site speed.",
  ["Set a sales and profit target.",
   "Choose the offer.",
   "Check you have enough stock of your best sellers.",
   "Put ad and email dates on a timeline."],
  30, "retention", "6.14", "15", ("growth", "Build your timeline"), "Profit, compared with your target"),
 (53, "Product launch", "Plan your next product launch",
  "A waitlist, early access for your best customers, launch day and a push halfway through turn a new product into an event.",
  ["Pick the launch date.",
   "Open a waitlist page now.",
   "Plan the emails and ads that build excitement.",
   "Plan a 24-hour push halfway through the launch."],
  20, "retention", "13.2", "15", ("growth", "Write the launch plan"), "Profit during the launch"),
 (54, "Stock", "Do a weekly stock check",
  "Running ads for a product that is about to sell out wastes money. Too much stock ties up cash. Know how many weeks your stock will last.",
  ["List how much stock you have of your top 10 products.",
   "Divide each by how many you sell in a week. That is your weeks of cover.",
   "Flag anything under 4 weeks or over 20 weeks.",
   "Plan reorders or promotions."],
  20, "numbers", "14.2", "17", ("growth", "Make the stock check for you"), None),
 (55, "Cash", "Make a 13-week cash plan",
  "Profit is not the same as cash in the bank. A simple plan shows when stock, ads and bills land, so busy season does not catch you short.",
  ["List the money coming in and going out for each of the next 13 weeks.",
   "Include stock orders and ad spend.",
   "Find the week with the lowest bank balance.",
   "If it looks tight, pick one fix, like a smaller order or a sale."],
  30, "numbers", "14.4", "17", None, None),
 # ---------- Stage 7: Grow bigger, work smarter ----------
 (56, "Grow a winner", "Spend more on a winning campaign, safely",
  "Raise budgets in small steps while profit holds. When that stops working, copy the winner into a new campaign.",
  ["Pick one campaign whose cost per sale has been under target for a week.",
   "Raise its budget by 20% in Ads Manager. You make this change yourself.",
   "Watch profit and MER for 3 days.",
   "If profit holds, repeat. If not, go back."],
  10, "ads", "2.7", "05", ("growth", "Tell you each budget step to make in Ads Manager"), "Profit and MER"),
 (57, "Test what works", "Turn one thing off to see what it really adds",
  "Meta and Google both claim the same sale. Turning one off for a week shows what is truly bringing in sales.",
  ["Choose one campaign or channel.",
   "Pause it for a week, or only in one area.",
   "Compare total sales and profit with the week before.",
   "Decide: keep it, cut it or change it."],
  15, "ads", "20.9", "06", None, "Total sales and profit"),
 (58, "New countries", "Check if selling in a second country makes sense",
  "Selling overseas multiplies what already works. Check people want it there and that you still make a profit after costs.",
  ["Check which countries already visit and buy.",
   "Work out your costs for that country.",
   "Check shipping times, costs and import taxes.",
   "Decide: test now or later."],
  20, "numbers", "15.1", "17", None, None),
 (59, "Hand it off", "Hand one regular task to someone else",
  "Your time is the scarcest thing you have. Hand off one repeat task so you can work on growth.",
  ["List the tasks you did this week.",
   "Mark the ones someone else could do.",
   "Write short steps for one of them.",
   "Give it to a team member, a freelancer or Helix."],
  20, "learning", "16.5", "18", None, None),
 (0, "AI helpers", "Give one weekly job to AI",
  "AI is good at repeat work: summing up reviews, drafting emails, writing ad versions and checking data. Pick one job, explain it clearly and check what it gives you.",
  ["Pick one weekly job, like a report, an email draft or a review summary.",
   "Write the background: your brand, your customer, your rules and an example.",
   "Run it and check every fact.",
   "Save your instructions so you can reuse them."],
  20, "learning", "17.2", "18", ("starter", "Set this up as a weekly Helix job"), None),
 (0, "Your setup", "Check your tools and choose your next focus",
  "Tools should save time, not add noise. Then pick your focus for the next six weeks and keep the daily habit going.",
  ["List your apps and what each costs per month.",
   "Cancel one you do not use (see the rules in Lesson 18.2).",
   "Pick your one focus for the next six weeks (Lesson 16.3).",
   "Come back tomorrow and keep your streak."],
  20, "learning", "18.2", "18", None, "Profit, every day"),
]
