# "Just starting" track: for new founders with little or no sales yet.
# Lighter lessons (5 to 15 minutes), in plain English. Same day format as curriculum_source.py:
# (unused, topic, title = today's action, why it matters, numbered steps, minutes, area,
#  lesson ref "M.L", SOP, doIt (tier, label) or None, what to watch or None)
# Run: python3 scripts/build_curriculum.py

STAGES = [
    (1, "Check your product and offer", 7),
    (2, "Get your store ready", 14),
    (3, "Your first small test campaign", 21),
]

D = [
 # ---------- Stage 1: Check your product and offer ----------
 (1, "Who it is for", "Write who your product is for",
  "If you try to sell to everyone, your ads and pages speak to no one. One clear sentence about your buyer makes every later step easier.",
  ["Finish this sentence: 'My product is for [person] who wants [result] but struggles with [problem].'",
   "Keep it under 25 words.",
   "Read it to a friend. Ask them to say it back in their own words.",
   "If they get it wrong, make the sentence simpler and try again.",
   "Save the final sentence. You will use it in your ads and on your home page."],
  10, "learning", "4.2", "16", None, None),
 (2, "Is there demand?", "Check that people already want it",
  "The cheapest test is the one you run before spending on ads. If people already search for, talk about and buy products like yours, you are in a good place.",
  ["Search Google for what you sell. Write down 3 competitors that come up.",
   "Read 20 reviews of those competitors. Note what people love and what they complain about.",
   "Search TikTok or Instagram for the product type. Do people post about it?",
   "Give your idea a score from 1 to 5 for demand. Under 3? Look at how to make the product or offer more different."],
  15, "learning", "3.7", "16", None, None),
 (3, "Your cost per sale", "Work out what one sale really costs you",
  "A sale can lose money even at a good price. You need to know every cost that comes with one order before you set prices or spend on ads.",
  ["Write your product cost (what you pay the supplier for one unit).",
   "Add packaging and the shipping you pay to send it.",
   "Add payment fees. Use about 3% of the price if you are not sure.",
   "Add the total. This is your cost per sale before ads.",
   "Price minus this cost is what you have left to pay for ads and keep as profit."],
  10, "numbers", "1.2", "02", ("free", "Work out your cost per sale from your prices"), None),
 (4, "A price that leaves profit", "Check your price leaves room for ads",
  "New stores often price too low and then cannot afford ads. A simple check now saves months of selling at a loss.",
  ["Take your price and your cost per sale from yesterday.",
   "Aim for a price of at least 3 times your product cost. Many small stores need this to cover ads and still make money.",
   "If you are below that, look at bundles, a higher-value version, or a cheaper supplier.",
   "Write down the most you could pay in ads for one sale and still break even: price minus cost per sale."],
  10, "numbers", "3.6", "04", None, None),
 (5, "Your promise", "Write your one-line promise",
  "People decide in seconds. A clear promise tells them what they get and why it is better, before they scroll away.",
  ["Write one line: the result your customer gets, not the features.",
   "Add why it is different, in plain words. For example: 'Soft as cotton, dries in an hour.'",
   "Cut any word a 12-year-old would not understand.",
   "Put the line at the top of your home page and under your product title."],
  10, "site", "3.2", "04", ("starter", "Draft 5 promise lines for you to choose from"), "Conversion rate"),
 (6, "Remove the risk", "Make buying feel safe",
  "A new store has no reputation yet. Clear returns, a simple guarantee and visible contact details make a stranger feel safe enough to buy.",
  ["Write your returns rule in one plain sentence, for example '30 days to change your mind'.",
   "Add it near the Add to cart button and in your footer.",
   "Show a real email address or chat button on every page.",
   "If you can, add a guarantee in one line."],
  10, "site", "3.5", "04", None, "Conversion rate"),
 (7, "First proof", "Collect your first reviews and photos",
  "People trust other customers more than they trust you. Even 5 honest reviews with photos make a big difference for a new store.",
  ["List everyone who has bought or tried the product, including friends and family.",
   "Ask each one for a short honest review and, if possible, a photo.",
   "Install a review app on your store if you do not have one.",
   "Add the best 3 reviews near the top of your product page."],
  15, "site", "3.3", "16", None, "Conversion rate"),

 # ---------- Stage 2: Get your store ready ----------
 (8, "The 5-second test", "Check your home page makes sense in 5 seconds",
  "Visitors who are confused leave. Your home page must say what you sell and who it is for straight away.",
  ["Open your home page on your phone.",
   "Ask someone new to look for 5 seconds, then tell you what you sell and who it is for.",
   "If they cannot, put your one-line promise and a clear product photo at the very top.",
   "Have one main button, such as 'Shop now', above the fold (the part you see without scrolling)."],
  10, "site", "9.2", "11", ("free", "Run a store check-up on your home page"), "Conversion rate"),
 (9, "Product page basics", "Tick off the product page basics",
  "Most buying decisions happen on the product page. A few basics answer the questions that stop people buying.",
  ["Use at least 4 clear photos, including one that shows the size or the product in use.",
   "Put the price, your promise line and the Add to cart button near the top.",
   "Answer the main worries in short lines: size or fit, quality, shipping time, returns.",
   "Add your best reviews."],
  15, "site", "9.5", "11", ("starter", "Draft product page copy for your top product"), "Conversion rate"),
 (10, "Shipping and returns", "Write shipping and returns in plain words",
  "Surprise shipping costs are one of the top reasons people leave at checkout. Say the cost and timing clearly, early.",
  ["Write how long delivery takes and what it costs, in one or two lines.",
   "Show it on the product page, not only on a policy page.",
   "If you offer free shipping over an amount, show that amount clearly.",
   "Write your returns steps as 3 simple numbered steps."],
  10, "site", "9.6", "11", None, "Conversion rate"),
 (11, "Speed and phone check", "Check your store on a phone",
  "Most shoppers visit on a phone. A slow or clumsy mobile store wastes every ad dollar you spend later.",
  ["Open your store on your phone using mobile data, not wifi.",
   "Time how long the home page and a product page take to load. Aim for about 3 seconds or less.",
   "Try to buy something. Note anything that is hard to tap or read.",
   "Remove apps you do not use and shrink very large images."],
  10, "site", "9.4", "11", None, "Conversion rate"),
 (12, "Start your list", "Add an email sign-up and a welcome email",
  "Most visitors will not buy on the first visit. An email sign-up lets you invite them back for free.",
  ["Turn on a sign-up pop-up in your email tool (for example Klaviyo or Shopify Email).",
   "Offer a small reason to join, such as a first-order gift or early access.",
   "Write one welcome email: say hello, repeat your promise, show your best seller.",
   "Test it by signing up yourself."],
  15, "retention", "10.1", "13", ("starter", "Draft your welcome email"), "Email sign-ups"),
 (13, "Tracking", "Install the Meta pixel and Google tag",
  "Without tracking you cannot tell which ads bring sales. Set it up before you spend a single dollar on ads.",
  ["In Shopify, install the Facebook and Instagram app and the Google app.",
   "Connect your Meta account and turn on the pixel (a small piece of code that tells Meta when someone buys).",
   "Connect your Google account so Google can see your sales too.",
   "Place a small test order and check it shows up in both."],
  15, "ads", "20.1", "05", None, None),
 (14, "Daily numbers", "Start your 2-minute morning numbers",
  "Even with few sales, writing down yesterday's sales, orders and ad spend each morning builds the habit that later tells you what is working.",
  ["Go to Today and find the 'Update yesterday' box.",
   "Type yesterday's sales and orders. Zero is fine.",
   "Type any ad spend.",
   "Press Save. Do this every morning from now on."],
  5, "numbers", "1.6", "02", None, "Profit, every day"),

 # ---------- Stage 3: Your first small test campaign ----------
 (15, "Test budget", "Set your test budget and your stop rule",
  "Your first campaign is a test, not a bet. Decide how much you can afford to learn with, and when to stop, before you start.",
  ["Pick a total test budget you can afford to lose, for example $150 to $300.",
   "Split it over 7 to 10 days. That is often $20 to $30 a day.",
   "Write your stop rule: if one ad spends twice your break-even cost per sale with no sale, turn it off.",
   "Write your keep rule: if an ad gets sales at or under your break-even cost, keep it running."],
  10, "numbers", "1.5", "06", None, "Ad cost per sale (CPA) compared with your break-even"),
 (16, "Simple ads", "Film 3 simple ads on your phone",
  "You do not need a studio. Simple, real-looking phone videos often beat polished ads, especially for new brands.",
  ["Film 3 short videos (10 to 20 seconds) on your phone in good daylight.",
   "Video 1: you or a customer using the product. Video 2: a close-up of the key detail. Video 3: the problem, then your product solving it.",
   "Hold the phone upright (vertical).",
   "Add short captions, because many people watch with the sound off."],
  15, "ads", "19.10", "08", None, None),
 (17, "Words that stop the scroll", "Write the first line for each ad",
  "The first 3 seconds and the first line decide if anyone watches. One clear line about the problem or result works best.",
  ["For each video, write a first line that names the problem or the result, for example 'Tired of bottles that leak in your bag?'",
   "Write a short main text: the promise, one proof point and the offer.",
   "Add a clear button such as 'Shop now'.",
   "Read each one out loud. Cut anything that sounds like an ad from a big company."],
  10, "ads", "5.7", "07", ("starter", "Draft 3 opening lines and ad text for each video"), None),
 (18, "Build the test", "Set up your first campaign, paused",
  "Building the campaign paused lets you check everything calmly before any money is spent.",
  ["In Ads Manager, create a Sales campaign.",
   "Set the daily budget from Day 15. Leave the audience broad (your country, adults).",
   "Add your 3 ads and link them to your best product page.",
   "Leave it paused. Check the link, the pixel and the text, then save."],
  15, "ads", "20.3", "05", ("starter", "Build the test campaign as a paused draft in your account"), None),
 (19, "Launch and wait", "Launch the test and leave it alone",
  "New campaigns go through a learning phase while Meta works out who to show them to. Changing things every day restarts it and wastes money.",
  ["Press Launch on your paused campaign.",
   "Do not change budgets or ads for 3 days unless an ad hits your stop rule.",
   "Keep doing your 2-minute morning numbers.",
   "Note each day's spend, clicks and any sales."],
  5, "ads", "7.5", "06", None, "Ad cost per sale (CPA) and profit"),
 (20, "Read the results", "Read what your test is telling you",
  "Even without many sales, the numbers show where the problem is: the ad, the page, or the offer.",
  ["Check how many people clicked (CTR, the share of viewers who click). Under about 1% often means the ad needs work.",
   "If people click but do not add to cart, the product page or price is the problem.",
   "If people add to cart but do not buy, check shipping costs and checkout.",
   "Write down the one biggest problem."],
  15, "ads", "20.7", "06", None, "Ad cost per sale (CPA) and profit"),
 (21, "Your next step", "Decide what to do next",
  "A test ends with a decision. Keep what works, fix the biggest problem, and plan the next small test.",
  ["Turn off any ad that broke your stop rule.",
   "Keep any ad that got sales at or under break-even.",
   "Pick one fix for the biggest problem from yesterday: a new ad, a page change, or a better offer.",
   "When you are getting regular sales, switch to the Growing track in Settings."],
  10, "learning", "7.6", "06", None, None),
]
