# Source of truth for the day-by-day curriculum.
# Run: python3 scripts/build_curriculum.py  (writes src/lib/seed/curriculum.json and docs/daily-curriculum.md)
# Fields: day, stage, topic, title (the action), lesson (short lesson), steps, minutes, area, lesson ref "M.L", sop, doIt (tier,label) or None

# (id, name, last day of the stage). Days are renumbered in order by build_curriculum.py.
STAGES = [
    (1, "Know your numbers", 7),
    (2, "Make the store convert", 17),
    (3, "Capture and keep customers", 26),
    (4, "Brand, creative and ads engine", 46),
    (5, "Google and more channels", 52),
    (6, "Offers, promotions and peak", 58),
    (7, "Scale and systems", 64),
]

D = [
 # ---------- Stage 1 ----------
 (1, "Profit, not revenue", "Set up your cost drivers",
  "Revenue tells you how busy you were. Contribution profit tells you if it was worth it: sales minus product cost, shipping, fees and marketing. Today you give Helix the costs it needs to calculate that every day.",
  ["Open the Scorecard settings card.", "Enter monthly fixed costs (staff, software, rent, your wage).", "Enter a monthly revenue target you believe in.", "Enter a target MER, or use 30% for now.", "Save."],
  10, "numbers", "1.2", "02", ("free", "Pre-fill cost drivers from your store data")),
 (2, "The daily scorecard", "Enter yesterday's numbers",
  "A two-minute scorecard each morning is the heartbeat of a growing store. You will see contribution profit, MER and your flags before you make any decision.",
  ["Open the Scorecard and add yesterday: orders, sales, discounts, refunds.", "Add product cost, shipping and payment fees.", "Add ad spend for each channel.", "Check the green, amber and red flags.", "Write one line on what you will do today."],
  5, "numbers", "1.3", "02", ("starter", "Sync yesterday's numbers automatically")),
 (3, "Break-even targets", "Work out your break-even ROAS and CPA",
  "Every ad decision needs a line in the sand. Break-even ROAS is 1 ÷ (1 − variable cost %). Break-even CPA is what you can spend to win an order without losing money on it.",
  ["Open the Scorecard and read your variable cost ratio.", "Note break-even ROAS and break-even CPA from the channel card.", "Set a good CPA for cold traffic (about AOV × target MER × 2).", "Write all three on a sticky note near your desk."],
  10, "numbers", "1.5", "02", None),
 (4, "Find the constraint", "Diagnose what is holding profit back",
  "Growth stalls for one of three reasons: costs are too high, conversion is too low, or there is not enough traffic. Fixing the wrong one wastes months.",
  ["Compare your numbers with the healthy ranges in Lesson 1.4.", "Mark which KPI is furthest out of range.", "Pick the matching situation in Lesson 2.2.", "Choose one fix to work on this week."],
  15, "numbers", "2.2", "03", ("starter", "Run the diagnosis on your data")),
 (5, "Store audit", "Pick your top 3 audit fixes",
  "Helix crawls your store and checks speed, proof, shipping clarity, email capture and trust. Today you choose the three fixes worth the most and put them in your plan.",
  ["Open Insights and read the site audit findings.", "Sort by impact.", "Pick three you can do in under an hour each.", "Schedule them for this week."],
  10, "site", "9.2", "01", ("free", "Run a fresh site audit")),
 (6, "Customer research", "Read 30 reviews and 10 support emails",
  "Your customers already wrote your best ads and product page copy. Their words reveal the problem, the doubt and the moment they decided to buy.",
  ["Export or open your last 30 reviews and 10 support emails.", "Copy repeated phrases into a doc under: problem, doubt, result.", "Note the top 3 objections.", "Star 5 lines that could become ad hooks."],
  20, "learning", "4.2", "16", ("starter", "Summarise reviews into themes and hooks")),
 (7, "Weekly rhythm", "Run your first weekly review",
  "Daily actions compound when you look back each week. Ten minutes on Sunday or Monday keeps you honest about what worked.",
  ["Read your week-to-date numbers on the Scorecard.", "List what you did this week.", "Write one thing you learned.", "Choose next week's single priority."],
  10, "learning", "16.2", "18", None),
 # ---------- Stage 2 ----------
 (8, "Site speed", "Fix the biggest mobile speed problem",
  "Most of your shoppers are on phones. A slow product page loses buyers before they see your offer.",
  ["Open Insights and check the PageSpeed result.", "Compress oversized images on your top product page.", "Remove one app or script you no longer use.", "Re-test and note the new score."],
  20, "site", "9.4", "11", ("growth", "Draft a speed fix list for your developer")),
 (9, "Proof", "Add photo reviews above the fold on your best seller",
  "Proof near the price is one of the cheapest ways to lift conversion, and every channel benefits.",
  ["Open your best-selling product page.", "Pick 3 reviews with photos that answer common doubts.", "Place them under the price or add-to-cart area.", "Check on your phone."],
  10, "site", "9.2", "11", ("growth", "Draft the review block layout")),
 (10, "Offer clarity", "Answer your top 3 objections on the product page",
  "If a shopper has to guess about fit, quality or delivery, they leave. Answer the doubts before they ask.",
  ["Take the 3 objections from Day 6.", "Write a one-line answer for each.", "Add them as short FAQs or icons near add to cart.", "Link your guarantee."],
  15, "site", "3.3", "04", ("starter", "Write the objection answers for you")),
 (11, "Shipping", "Set a free shipping threshold that lifts order value",
  "A threshold set a little above your average order nudges people to add one more item without giving away margin.",
  ["Check your AOV on the Scorecard.", "Set the threshold at about 1.2 to 1.4 × AOV.", "Show it in the announcement bar and the cart.", "Check the margin still works."],
  15, "site", "9.11", "12", ("growth", "Set up the threshold message (with approval)")),
 (12, "Checkout", "Remove one checkout friction",
  "Shoppers who add to cart but do not check out usually hit a surprise: shipping cost, limited payment options or a forced account.",
  ["Do a test checkout on your phone.", "Turn on express wallets and buy now pay later if missing.", "Make guest checkout available.", "Show delivery time before the last step."],
  15, "site", "9.10", "11", None),
 (13, "Home page", "Make your hero say what you sell and why it is better",
  "Visitors decide in seconds. Your first screen needs a clear headline, the main benefit, proof and one button.",
  ["Look at your home page on a phone.", "Rewrite the headline: what it is plus the main benefit.", "Add a proof line (rating, customers, press).", "Use one clear button."],
  15, "site", "9.5", "11", ("starter", "Write 3 headline options")),
 (14, "Risk reversal", "Write a guarantee you are proud of",
  "A clear guarantee removes the fear of a bad purchase. It often lifts conversion more than a discount.",
  ["Check your current returns policy.", "Write a simple promise in one sentence.", "Add it to product pages, cart and FAQ.", "Make sure your team can honour it."],
  10, "site", "3.5", "04", ("starter", "Draft your guarantee wording")),
 (15, "Bundles", "Create one bundle that raises AOV",
  "Bundles help shoppers buy the complete solution and lift order value without a store-wide discount.",
  ["Find products often bought together.", "Create one bundle with a small saving or a gift.", "Feature it on the related product pages.", "Track its sales on the Scorecard product table."],
  20, "site", "3.6", "12", ("growth", "Suggest bundles from your order data")),
 (16, "Navigation", "Tidy your menu and best collection page",
  "If people cannot find it, they cannot buy it. Clear collections and filters make browsing easy.",
  ["Limit your menu to the categories people shop by.", "Put best sellers first in your top collection.", "Add filters for size or type if relevant.", "Check search returns sensible results."],
  20, "site", "9.2", "11", None),
 (17, "Post-purchase", "Add a one-click post-purchase offer",
  "The moment after buying is when trust is highest. A relevant add-on at a small saving lifts AOV.",
  ["Choose a low-cost complementary product.", "Set up a post-purchase offer in your checkout app.", "Keep it to one offer.", "Review take rate next week."],
  15, "site", "9.10", "12", ("growth", "Configure the offer (with approval)")),
 # ---------- Stage 3 ----------
 (18, "Email capture", "Launch a pop-up that converts above 3%",
  "Every visitor who leaves without buying and without subscribing is gone. A good pop-up turns traffic into a list you own.",
  ["Pick an incentive (10% off, free shipping, or a guide).", "Show it after 8 to 10 seconds or on exit intent.", "Ask for email, then phone on step two.", "Track the sign-up rate weekly."],
  20, "retention", "10.1", "13", ("growth", "Draft the pop-up copy and settings")),
 (19, "Welcome series", "Turn on your welcome series",
  "New subscribers are at peak interest. A 3 to 6 email welcome series introduces your brand and converts first orders while you sleep.",
  ["Open Email automation in Helix.", "Review the welcome drafts.", "Approve, then check it is live in your email platform.", "Send yourself a test."],
  20, "retention", "10.2", "13", ("growth", "Draft and set up the welcome series")),
 (20, "Checkout recovery", "Turn on abandoned checkout",
  "People who started checkout were close. A timely, helpful reminder brings many back, usually without a discount.",
  ["Open Email automation.", "Review the abandoned checkout drafts.", "Keep incentives for new customers only, last message only.", "Approve and test."],
  15, "retention", "10.2", "13", ("growth", "Draft and set up abandoned checkout")),
 (21, "Cart and browse", "Add cart and browse abandonment",
  "Not everyone reaches checkout. Gentle cart and browse reminders help undecided shoppers choose.",
  ["Review the cart and browse drafts.", "Add a product guide or best-sellers block.", "Exclude people who already ordered.", "Approve and test."],
  15, "retention", "10.2", "13", ("growth", "Draft and set up both flows")),
 (22, "After the order", "Set up post-purchase and review requests",
  "What happens after the first order decides if there is a second. Thank, guide and ask for a review at the right time.",
  ["Review the post-purchase and review request drafts.", "Time the review ask to when results show.", "Add usage tips.", "Approve and test."],
  15, "retention", "10.2", "13", ("growth", "Draft and set up both flows")),
 (23, "Repeat customers", "Plan win-back, replenishment and VIP",
  "Lapsed and loyal customers need different messages. Win-back reminds, replenishment times the reorder, VIP rewards your best people.",
  ["Find your typical days between orders.", "Choose which of the three flows fit your products.", "Review the drafts.", "Approve the ones that fit."],
  20, "retention", "10.12", "13", ("growth", "Draft and set up the flows that fit")),
 (24, "Email campaigns", "Plan two campaign emails a week",
  "Flows catch moments; campaigns build the relationship. Mix education, stories, product and offers.",
  ["Pick two weekly send days.", "Plan 4 weeks of topics: story, education, best sellers, new arrivals.", "Segment engaged vs unengaged.", "Schedule next week's first send."],
  20, "retention", "10.5", "14", ("growth", "Draft next week's emails")),
 (25, "SMS and chat", "Decide if SMS or WhatsApp fits your store",
  "SMS and chat are powerful for launches and recovery but cost more per message. Use them for moments that matter.",
  ["Check your platform's SMS cost.", "Add phone capture as step two of your pop-up.", "Use SMS for launches, sale starts and checkout recovery.", "Always include opt-out."],
  10, "retention", "10.10", "13", None),
 (26, "List growth", "Plan a list-building competition",
  "A well-run giveaway with partner brands can add thousands of subscribers before a big sale.",
  ["Choose a prize your ideal customer wants (not cash).", "Invite 2 to 4 non-competing partner brands.", "Set entry: email plus phone, bonus entries for sharing.", "Plan a welcome offer for new entrants."],
  20, "retention", "11.3", "14", ("growth", "Draft the competition plan and partner outreach")),
 # ---------- Stage 4 ----------
 (27, "Brand core", "Write your brand core in one page",
  "Clear brand foundations make every ad, email and page easier: who you serve, what you believe, how you sound.",
  ["Write your mission in one sentence.", "Describe your best customer.", "List 3 things you do differently.", "Choose 3 words for your tone."],
  20, "learning", "4.1", "16", ("starter", "Draft your brand core from your site")),
 (0, "Social profile", "Make your Instagram and TikTok profiles convert",
  "Many people who see your ad tap your profile before they buy. Your bio, link, highlights and pinned posts should prove you are real, show what you sell and give the next step.",
  ["Rewrite your bio: what you sell, your proof, a reason to tap now.", "Point the link to a fast page with 3 to 5 clear options and UTMs.", "Create highlights: Reviews, Best sellers, How to use, Shipping.", "Pin your best product video, strongest proof and brand story."],
  20, "learning", "21.2", "16", ("starter", "Audit your profiles and draft the bio and highlights")),
 (0, "Posting rhythm", "Set a posting cadence you can keep for 12 weeks",
  "Consistency beats volume. A simple weekly rhythm built on proof, education, story and product keeps your profile alive and feeds your ads with tested content.",
  ["Choose your cadence for your stage (Lesson 21.4).", "Plan next week across the four pillars.", "Batch-film on one day.", "Schedule the posts."],
  25, "learning", "21.4", "16", ("starter", "Draft a 4-week content calendar")),
 (0, "Organic reach", "Test hooks with trial reels and social search",
  "Social platforms are search engines now. Say your keywords out loud and on screen, and test new hooks on non-followers before posting to everyone.",
  ["Pick your best organic video.", "Make 3 new openings with keywords spoken and on screen.", "Post them as trial or test reels where available.", "After 24 hours, post the winner to everyone and log it as an ad candidate."],
  20, "learning", "21.5", "16", None),
 (28, "Creative strategy", "Map angles to awareness stages",
  "Different people need different messages: some do not know they have the problem, some are comparing options. Your creative should cover each stage.",
  ["List 3 problems your product solves.", "Write one angle for unaware, problem-aware and solution-aware buyers.", "Pick one angle to test first.", "Save them in your angle bank."],
  20, "ads", "5.5", "07", ("starter", "Suggest angles for each stage")),
 (29, "Hooks", "Build a bank of 20 hooks",
  "The first three seconds decide if anyone watches. Mine hooks from reviews, support emails and competitor complaints.",
  ["Use your Day 6 notes.", "Write 20 hooks across types: bold claim, call out, curiosity, one-star rebuttal, result first.", "Pair each with a visual idea.", "Star your top 5."],
  20, "ads", "19.8", "07", ("starter", "Write 20 hooks from your reviews")),
 (30, "Creators", "Shortlist 10 creators",
  "Real people explaining why they love your product build trust faster than brand ads. Fit beats follower count.",
  ["Search the problems you solve on Instagram and TikTok.", "Check your tagged posts and customers.", "Score each creator out of 10.", "Save 10 to your creator tracker."],
  20, "ads", "19.2", "08", ("starter", "Find creators that match your niche")),
 (31, "Outreach and affiliates", "Contact 5 creators with a gifting and affiliate offer",
  "Start with product, pay more once content performs, and give creators an offer that does not clash with your own pop-up code.",
  ["Write a personal message mentioning one of their videos.", "Offer product plus your affiliate deal.", "Check your public offer does not beat their code.", "Send 5 today and log them."],
  20, "ads", "19.5", "08", ("starter", "Draft personal outreach messages")),
 (32, "UGC brief", "Write a UGC brief",
  "A clear brief is the difference between usable content and wasted product. Hooks, key message, proof and deliverables in one page.",
  ["Open the UGC brief template in Lesson 19.12.", "Fill in key message, proof points and must-not-say.", "Add 3 hooks to film separately.", "Send to your creators."],
  20, "ads", "19.12", "08", ("starter", "Fill in the brief for you")),
 (33, "Scripting", "Script one 30-second video ad",
  "Hook, problem, product and proof, objection, call to action. A simple structure keeps videos tight and selling.",
  ["Pick your top angle and hook.", "Write the script in five parts.", "Read it aloud and cut anything that drags.", "Write 3 alternative hooks."],
  20, "ads", "19.9", "07", ("starter", "Write 3 script options")),
 (34, "Shoot and edit", "Shoot and edit a phone video",
  "You do not need a studio. Natural light, clear audio, quick cuts and captions beat polish on social feeds.",
  ["Film by a window, vertical, with the back camera.", "Shoot the hook 3 ways.", "Edit: fast cuts, captions, text hook in frame one.", "Export 9:16 and 4:5."],
  45, "ads", "19.11", "07", None),
 (35, "Tracking", "Check your tracking is trustworthy",
  "Wrong data leads to wrong decisions. Confirm purchases are tracked once, with the right value.",
  ["Check pixel and server events are connected.", "Make Purchase the only primary conversion.", "Place a test order and confirm value.", "Add UTMs to your ads."],
  15, "ads", "20.1", "05", ("starter", "Run a tracking check")),
 (36, "Audiences", "Set up your target audiences",
  "Broad targeting with strong creative is the default, but you still need custom audiences for warm and hot layers and exclusions.",
  ["Set account audience segments (engaged, existing customers).", "Create visitors 30/180, add to cart, checkout, purchasers, engagers.", "Upload your customer list.", "Create one lookalike for later tests."],
  20, "ads", "20.2", "05", ("starter", "Create the audiences in your account (with approval)")),
 (37, "Define the campaign", "Fill in a campaign brief",
  "Every campaign starts with numbers and a kill rule, not with Ads Manager. The brief makes the decision obvious later.",
  ["Open the campaign brief template.", "Set target CPA, budget and test period.", "Choose objective, layer and structure.", "Write the kill and scale rules."],
  20, "ads", "6.16", "05", ("starter", "Fill in the brief with you")),
 (38, "Campaign setup", "Build your first structured Meta campaign",
  "Follow the setup steps once, carefully, and you can repeat them for every test.",
  ["Create a Sales campaign with your naming convention.", "Set budget at 2 to 3 × target CPA per day.", "Add 3 to 6 ads testing one variable.", "Check enhancements and preview, then press Launch yourself."],
  30, "ads", "20.3", "05", ("starter", "Build it in your account as paused drafts. You press Launch")),
 (39, "Structure", "Match your account structure to your spend",
  "Small budgets need simple structures. Add layers only as spend grows.",
  ["Find your daily spend band in Lesson 6.4.", "Compare with your current campaigns.", "Merge or pause what does not fit.", "Rename campaigns to the convention."],
  15, "ads", "6.4", "05", ("starter", "Suggest a restructure")),
 (40, "Daily grading", "Grade your ads and pause the drains",
  "Ten minutes a day: pause ads that spent twice your good CPA without results, feed the winners, leave learning ads alone.",
  ["Open the Campaign tracker.", "Read each Helix recommendation.", "Pause kills. Raise scales by up to 20% yourself in Ads Manager.", "Log what you changed."],
  10, "ads", "7.6", "06", ("starter", "Pause the drains for you and prepare budget changes for you to make")),
 (41, "Analysis", "Find where your funnel leaks",
  "Good ad, poor sales means the page. Lots of carts, few checkouts means checkout. Strong site, weak clicks means creative. Diagnose before you fix.",
  ["Open Insights.", "Read the cross-diagnosis findings.", "Match each to the table in Lesson 20.7.", "Pick one fix for this week."],
  15, "ads", "20.7", "06", ("starter", "Explain your funnel leaks")),
 (42, "Partnership ads", "Launch one partnership ad",
  "Running a creator's post from their handle shows a familiar face instead of a brand ad. Add it to your normal campaign as a new batch.",
  ["Ask a creator with a strong post for permission.", "Connect through the platform's partnership tools.", "Add the post to your cold campaign.", "Judge it on the same rules."],
  20, "ads", "19.6", "08", ("starter", "Add it to your campaign as a paused ad")),
 (43, "Creative iteration", "Run your weekly creative report",
  "Winners tell you what to make next. Iterate on the winning concept with new hooks, creators and formats.",
  ["List last week's top 3 ads by CPA and hook rate.", "Write why each won.", "Brief 4 to 8 new variations.", "Retire tired ads."],
  20, "ads", "5.11", "07", ("starter", "Build the creative report")),
 # ---------- Stage 5 ----------
 (44, "Product feed", "Rewrite titles for your top 10 products",
  "Google Shopping matches searches to your feed. Titles with the words people search are the biggest lever.",
  ["Find search terms that convert.", "Rewrite titles: brand, product type, key attribute, size or colour.", "Check images and prices.", "Resubmit the feed."],
  25, "ads", "8.2", "09", ("starter", "Rewrite feed titles (with approval)")),
 (45, "Google structure", "Set up brand search and feed-only PMax",
  "Keep cheap brand searches in their own campaign, and let PMax prospect with your feed while brand is excluded.",
  ["Create or check a brand search campaign.", "Create feed-only PMax with brand excluded.", "Start with maximise conversion value.", "Note the date for review."],
  30, "ads", "20.4", "09", ("starter", "Build both campaigns as paused drafts")),
 (46, "Search terms", "Add negatives from your search terms",
  "Search terms with spend and no sales are pure waste. Ten minutes a week stops the leak.",
  ["Open the search terms report.", "Sort by cost.", "Add irrelevant terms as negatives.", "Move converting terms into titles and keywords."],
  10, "ads", "8.8", "09", ("starter", "Find and add negatives (with approval)")),
 (47, "TikTok", "Check if TikTok is right for you yet",
  "TikTok rewards native, entertaining content and volume. Be ready before you spend.",
  ["Check the readiness list in Lesson 12.1.", "Post 3 organic videos this week.", "Reuse your best UGC as Spark ads later.", "Decide: now or next quarter."],
  15, "ads", "12.1", "10", None),
 (48, "Search and discovery", "Fix SEO basics on your top pages",
  "Organic search is free traffic that compounds. Start with titles, descriptions and useful content on your best pages.",
  ["Write unique titles and meta descriptions for top 5 pages.", "Add helpful copy to your top collection.", "Fix broken links.", "Submit your sitemap."],
  25, "site", "12.8", "10", ("growth", "Draft titles and descriptions")),
 (49, "AI search", "Get ready for AI shopping assistants",
  "Shoppers now ask assistants for recommendations. Clean product data and clear policies make you easier to recommend.",
  ["Check product attributes and descriptions are complete.", "Make return and shipping policies clear.", "Check eligibility for agentic storefronts in your platform.", "Add FAQ content to top products."],
  15, "site", "12.9", "10", None),
 # ---------- Stage 6 ----------
 (50, "Promotional rhythm", "Map your next 90 days of promotions",
  "Planned moments beat random discounts. Mix launches, value-adds and a few real sales.",
  ["List key dates in your market.", "Plan one moment per month: launch, gift edit or sale.", "Decide offer type for each.", "Add to your calendar."],
  20, "retention", "13.1", "15", ("growth", "Draft your promo calendar")),
 (51, "Sale offers", "Design a sale offer that protects margin",
  "Tiered offers, gifts and bundles often beat blanket discounts. Check every offer against your break-even numbers.",
  ["Choose offer type: tiered, gift, bundle or percent.", "Model margin on the Scorecard.", "Plan a mid-sale boost.", "Write the offer in one line."],
  20, "retention", "13.4", "15", ("growth", "Model offer options")),
 (52, "Black Friday", "Start your Black Friday plan",
  "The biggest sales window of the year is decided weeks before. Target, offer, stock, list, creative and site speed.",
  ["Set the revenue target.", "Choose the offer.", "Check stock for best sellers.", "Book creative and email dates on the timeline."],
  30, "retention", "6.14", "15", ("growth", "Build your timeline")),
 (53, "Launches", "Plan your next product launch",
  "Waitlist, VIP early access, launch day and a mid-launch push turn a new product into an event.",
  ["Pick the launch date.", "Open a waitlist page now.", "Plan hype emails and creative.", "Plan the 24-hour mid-launch push."],
  20, "retention", "13.2", "15", ("growth", "Draft the launch plan")),
 (54, "Stock", "Run a weekly stock snapshot",
  "Ads on products that are about to sell out waste money; overstock ties up cash. Know your weeks of cover.",
  ["List stock on hand for top 10 products.", "Divide by weekly sales to get weeks of cover.", "Flag under 4 weeks and over 20 weeks.", "Plan reorders or promotions."],
  20, "numbers", "14.2", "17", ("growth", "Build the stock snapshot")),
 (55, "Cash", "Build a 13-week cash forecast",
  "Profit is not cash. A simple forecast shows when stock, ads and bills hit, so peak season does not catch you short.",
  ["List cash in and out for the next 13 weeks.", "Include stock orders and ad spend.", "Find the lowest point.", "Pick a lever if it is tight."],
  30, "numbers", "14.4", "17", None),
 # ---------- Stage 7 ----------
 (56, "Scaling", "Scale a winner safely",
  "Raise budgets in steps while MER holds. When vertical steps stop working, copy winners into new campaigns.",
  ["Pick one campaign with CPA under target for a week.", "Raise the budget by 20% in Ads Manager (you make this change).", "Watch MER for 3 days.", "Repeat or hold."],
  10, "ads", "2.7", "05", ("growth", "Prepare each budget step for you to make in Ads Manager")),
 (57, "Attribution", "Run a simple holdout test",
  "Platforms all claim the same sale. A holdout shows what is truly adding sales.",
  ["Choose one campaign or channel.", "Pause it for a week (or in one region).", "Compare total sales and MER.", "Decide to keep, cut or change."],
  15, "ads", "20.9", "06", None),
 (58, "New markets", "Check if a second country makes sense",
  "Expansion multiplies what already works. Check demand and unit economics before you spend.",
  ["Check where traffic and orders already come from.", "Recalculate costs for that country.", "Check shipping and duties.", "Decide: test now or later."],
  20, "numbers", "15.1", "17", None),
 (59, "Team and focus", "Delegate one recurring task",
  "Your time is the scarcest resource. Hand off one repeatable task so you can work on growth.",
  ["List tasks you did this week.", "Mark the ones someone else could do.", "Write a short SOP for one.", "Hand it to a team member, freelancer or Helix."],
  20, "learning", "16.5", "18", None),
 (0, "AI for operators", "Hand one weekly job to AI",
  "AI is best at the repeatable work: summarising reviews, drafting emails, writing ad variants, checking data. Pick one job, give it clear context and check the output.",
  ["Pick one weekly task (report, email draft, review summary).", "Write the context: brand, customer, rules, examples.", "Run it and check every fact.", "Save the prompt so it is repeatable."],
  20, "learning", "17.2", "18", ("starter", "Set this up as a weekly Helix job")),
 (0, "Your operating system", "Review your tools and set your next cycle",
  "Tools should save time, not add noise. Then pick the next six-week priority and let the daily loop continue.",
  ["List your apps and their monthly cost.", "Cancel one you do not use (Lesson 18.2 rules).", "Choose your next six-week priority (Lesson 16.3).", "Keep your streak going tomorrow."],
  20, "learning", "18.2", "18", None),
]
