# Plain-English glossary. One line each. Used by the app (Words to know) and docs/glossary.md.
# (term, [other spellings to match], explanation)
G = [
 ("Profit", ["contribution profit", "contribution"], "What is left from sales after product cost, shipping, payment fees, discounts, refunds and ads. This is the number Helix cares about most."),
 ("Revenue", ["sales", "gross sales"], "All the money customers paid. It looks good, but it is not what you keep."),
 ("Fixed costs", [], "Bills that stay the same each month, like rent, software, staff and your own wage."),
 ("Variable costs", ["variable cost"], "Costs that grow with every order: product cost, shipping and payment fees."),
 ("Product cost", ["COGS", "cost of goods"], "What one item costs you to make or buy, including freight to your warehouse."),
 ("Margin", ["gross margin"], "The share of each sale you keep after product cost. A $100 sale with $40 product cost is a 60% margin."),
 ("AOV", ["average order value"], "Average order value: total sales divided by number of orders."),
 ("ROAS", ["return on ad spend"], "Return on ad spend: how many dollars of sales you get for each $1 of ads. ROAS 3 means $3 of sales for $1 of ads."),
 ("Break-even ROAS", [], "The ROAS where an order makes $0 profit after its costs. Below it, ads lose money."),
 ("CPA", ["cost per acquisition", "cost per sale", "cost per purchase"], "Cost per acquisition: how much ad money it took to get one sale."),
 ("Break-even CPA", [], "The most you can pay in ads for one sale before that sale stops making money."),
 ("Target CPA", ["good CPA"], "The cost per sale you aim for so each sale still leaves you profit."),
 ("MER", ["marketing efficiency ratio"], "All ad spend divided by all sales, as a percentage. MER 25% means $25 of ads for every $100 of sales."),
 ("Conversion rate", ["CR"], "Out of every 100 visits, how many end in an order. 2% means 2 orders per 100 visits."),
 ("Session", ["sessions"], "One visit to your store. One person can make several visits."),
 ("CTR", ["click-through rate", "outbound CTR"], "Click-through rate: out of every 100 people who saw your ad, how many clicked."),
 ("CPM", [], "Cost to show your ad 1,000 times."),
 ("Frequency", [], "How many times, on average, the same person saw your ad."),
 ("Hook rate", [], "Out of everyone who saw your video ad, the share who watched at least 3 seconds. It tells you if the opening grabs attention."),
 ("ThruPlay", ["thruplay rate"], "A video view of 15 seconds or more (or the whole video if it is shorter)."),
 ("Hook", ["hooks"], "The first line or first 3 seconds of an ad. Its only job is to make people stop scrolling."),
 ("Angle", ["angles"], "The reason to buy that an ad focuses on, like saving time or looking good."),
 ("Creative", ["creatives"], "The ad itself: the picture or video plus the words."),
 ("UGC", ["user-generated content"], "Photos and videos made by real customers or creators instead of the brand."),
 ("Creator", ["creators"], "A person who makes social content and can feature your product."),
 ("Partnership ad", ["partnership ads", "Spark ads", "Spark ad"], "An ad that runs from a creator's own account, so people see their name instead of yours."),
 ("Campaign", ["campaigns"], "The top level in an ad account. It holds the goal, like getting sales."),
 ("Ad set", ["ad sets"], "The middle level in Meta. It holds who sees the ads, where, and often the budget."),
 ("Learning phase", ["learning"], "The first days after you start or change an ad set, while Meta works out who to show it to. Results jump around, so wait."),
 ("Pixel", [], "A small piece of code on your store that tells Meta when someone views, adds to cart or buys."),
 ("Server events", ["Conversions API", "CAPI"], "Sales sent to Meta straight from your store's server, so fewer sales go untracked."),
 ("UTM", ["UTMs", "UTM tags"], "Tags added to the end of a link so your analytics can tell which ad or email a visitor came from."),
 ("Cold audience", ["cold", "prospecting"], "People who have never heard of you."),
 ("Warm audience", ["warm"], "People who know you: they visited, followed or watched your videos."),
 ("Hot audience", ["hot", "retargeting"], "People close to buying: they added to cart or started checkout."),
 ("Custom audience", ["custom audiences"], "A list Meta builds from your own data, like site visitors or customers."),
 ("Lookalike", ["lookalike audience"], "People Meta thinks are similar to a list you give it, like your best customers."),
 ("Broad targeting", ["broad"], "Letting Meta find buyers with few or no audience limits. Works best with strong ads."),
 ("Advantage+", ["Advantage+ audience"], "Meta's automatic settings that let its system choose audience, placements or budget for you."),
 ("PMax", ["Performance Max"], "A Google campaign type that shows your products across Search, Shopping, YouTube and more from one campaign."),
 ("Brand search", [], "Ads that show when people search your brand name. Cheap and usually very profitable."),
 ("Product feed", ["feed"], "The list of your products, prices and photos that Google and Meta read to make shopping ads."),
 ("Search terms", ["search terms report"], "The exact words people typed into Google before they saw or clicked your ad."),
 ("Negative keyword", ["negatives", "negative keywords"], "A word you tell Google never to show your ads for, to stop wasted clicks."),
 ("Landing page", [], "The page someone lands on after clicking an ad."),
 ("Above the fold", [], "The part of a page you see before you scroll."),
 ("Funnel", [], "The steps from seeing an ad to buying: visit, add to cart, checkout, order."),
 ("Add to cart rate", ["ATC rate"], "Out of every 100 visits, how many add something to the cart."),
 ("Express wallets", [], "One-tap payment options like Apple Pay, Google Pay and Shop Pay."),
 ("Buy now pay later", ["BNPL"], "Payment options like Afterpay or Klarna that let shoppers split the cost."),
 ("Free shipping threshold", ["threshold"], "The order amount where shipping becomes free, like 'Free shipping over $100'."),
 ("Bundle", ["bundles"], "Two or more products sold together, often with a small saving."),
 ("Post-purchase offer", ["upsell"], "A one-click extra offer shown right after someone buys."),
 ("Guarantee", ["risk reversal"], "A clear promise that removes the fear of a bad purchase, like a 30-day money-back promise."),
 ("Flow", ["flows", "automation"], "An email or text series that sends by itself when something happens, like a new sign-up."),
 ("Campaign email", ["campaign emails"], "A one-off email you send to your list, like a new arrival announcement."),
 ("Segment", ["segments"], "A smaller group of your list, like people who bought in the last 90 days."),
 ("Pop-up", [], "A box on your site that asks visitors for their email, often with a small reward."),
 ("Abandoned checkout", [], "When someone starts checkout but does not finish. A reminder email can bring them back."),
 ("LTV", ["lifetime value"], "How much a customer spends with you over time, not just on the first order."),
 ("Weeks of cover", [], "How many weeks your stock will last at the current sales speed."),
 ("Cash forecast", [], "A week-by-week list of money coming in and going out, so you can see tight weeks early."),
 ("SEO", ["search engine optimisation"], "Changes that help your store show up in Google without paying for ads."),
 ("Meta description", ["meta descriptions"], "The short summary under your page title in Google results."),
 ("Attribution", [], "Deciding which ad or channel gets credit for a sale."),
 ("Holdout test", ["holdout"], "Turning something off for a while (or in one area) to see how many sales it really adds."),
 ("KPI", ["KPIs"], "Key performance indicator: one of the few numbers you watch to know if things are working."),
 ("Organic", [], "Unpaid: posts, search results and word of mouth that you do not pay to show."),
]
